# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Dreva' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Dreva
  pod 'Firebase/Core'
  target 'DrevaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DrevaUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
